-- Query extracted from SSIS_SQLText
-- FlowSQLId: 46
-- FlowId: 46
-- DatabaseTypeId: 2
-- MinVersion: 8.5
-- MaxVersion: 999
-- Extracted on: 2025-05-25T17:11:39.333324

SELECT		posting_id, 
				version, 
				jobcode, 
				postingnumber, 
				CONVERT(VARCHAR(19), postingbegindate, 120) as postingbegindate, 
			    CONVERT(VARCHAR(19), postingenddate, 120) as postingenddate,
				postingactivedays, 
				rollupname, 
				ishotjob, 
				isactive, 
				positionnum, 
				soundfilelocation, 
				jobtype, 
				jobfunction, 
				specificjobfunction, 
				jobfamily, 
				jobcategory, 
				salaryfrequency, 
				salarycurrency, 
				positionlevel, 
				flsaexemptionstatus, 
				degreerequired, 
				postingstatus, 
				salarygradecode, 
				minimumsalary, 
				midrangesalary, 
				maximumsalary, 
				referralbonus, 
				relocation, 
				travelpercent, 
				minexperience, 
				contactemail, 
				contactphone, 
				isfulltime, 
				equestupdated, 
				openfordays, 
				jobindustry, 
				qualifier_id, 
				reportsto_id, 
				postingsite_id, 
				jobopening_id, 
				parentscript_id, 
				postingtoapply, 
				guuid, 
				CONVERT(VARCHAR(19), datecreated, 120) as datecreated, 
			    CONVERT(VARCHAR(19), datelastmodified, 120) as datelastmodified,
				createdby, 
				lastmodifiedby, 
				postingcreator_id, 
				customfield_id, 
				<BATCHDATE> as ExtractDate, 
				<BATCHDATE> as BatchDate, 
				<SOURCESKEY> as SourceSkey 
	 FROM posting 
	 WHERE (datelastmodified >= <FROMDATE_Q>)