-- Query extracted from SSIS_SQLText
-- FlowSQLId: 185
-- FlowId: 185
-- DatabaseTypeId: 2
-- MinVersion: 8.5
-- MaxVersion: 999
-- Extracted on: 2025-05-25T17:11:39.351706

SELECT	SPONSOREDJOB_ID
	,POSTING_ID
	,JOBBOARDNAME
	,ACTION
	,SPONSOREDJOBSTATUS
	,STATUS
	,SERVICEID
	,SETID
	,ORDERID
    ,TO_CHAR(DATETOPROCESS, 'YYYY-MM-DD HH24:MI:SS') as DATETOPROCESS
	,JOBTYPE
	,ISSHOWCOMPENSATION
	,TO_CHAR(STARTDATE, 'YYYY-MM-DD HH24:MI:SS') as JOBSTARTDATE
    ,TO_CHAR(ENDDATE, 'YYYY-MM-DD HH24:MI:SS') as JOBENDDATE
	,CLIENT_ID
	,LOCATION_ID
	,VERSION
	,TO_CHAR(datecreated, 'YYYY-MM-DD HH24:MI:SS') as datecreated
    ,TO_CHAR(datelastmodified, 'YYYY-MM-DD HH24:MI:SS') as datelastmodified
	,CREATEDBY
	,LASTMODIFIEDBY
	,<BATCHDATE> as ExtractDate, 
	<BATCHDATE> as BatchDate, 
	<SOURCESKEY> as SourceSkey 
	FROM sponsoredjob 
	WHERE (datelastmodified >= <FROMDATE_Q>) 