-- Query extracted from SSIS_SQLText
-- FlowSQLId: 25
-- FlowId: 25
-- DatabaseTypeId: 2
-- MinVersion: 8.5
-- MaxVersion: 999
-- Extracted on: 2025-05-25T17:11:39.331064


		
		SELECT LOCALEQUESTION_ID
			,VERSION
			,LOCALE_ID
			,QUESTION_ID
			,QUESTIONTEXT
			,		TO_CHAR(datecreated, 'YYYY-MM-DD HH24:MI:SS') AS DATECREATED
			,CREATEDBY
			,		TO_CHAR(DATELASTMODIFIED, 'YYYY-MM-DD HH24:MI:SS') AS DATELASTMODIFIED
			,LASTMODIFIEDBY
			,QUESTIONSUBTEXT
			,QUESTIONPOPUPTEXT
			,QUESTIONADDITIONALNOTESTEXT,
			<BATCHDATE> as ExtractDate, 
				<BATCHDATE> as BatchDate, 
				<SOURCESKEY> as SourceSkey 
		FROM LOCALE_QUESTION_ATAO
		WHERE 
			(DateCreated >= <FROMDATE_Q>  or DateLastModified >= <FROMDATE_Q> )
		