-- Query extracted from SSIS_SQLText
-- FlowSQLId: 168
-- FlowId: 168
-- DatabaseTypeId: 2
-- MinVersion: 8.5
-- MaxVersion: 999
-- Extracted on: 2025-05-25T17:11:39.349479

SELECT 
  jobbid_id, 
  version, 
  null atsstatus, 
  null atsstatusdate, 
  null atsstatusreason, 
  null customfield_id, 
  null islocked, 
  null isrehireeligible, 
  null isexplicitlyunlocked, 
  TO_CHAR(biddate, 'YYYY-MM-DD HH24:MI:SS') as biddate, 
  process_id, 
  prescreenscore, 
  prescreenrawscore, 
  averagescore, 
  mailstatus, 
  prescreenstatus, 
  bidstatus, 
  hmcbidstatus, 
  initialhmcbidstatus, 
  qualifier_id, 
  postingtype, 
  referredby_id, 
  person_id, 
  application_id, 
  location_id, 
  datachannel, 
  TO_CHAR(datecreated, 'YYYY-MM-DD HH24:MI:SS') datecreated, 
  TO_CHAR(datelastmodified, 'YYYY-MM-DD HH24:MI:SS') datelastmodified, 
  TO_CHAR(datelockends, 'YYYY-MM-DD HH24:MI:SS') datelockends, 
  TO_CHAR(dateapplicationexpires, 'YYYY-MM-DD HH24:MI:SS') dateapplicationexpires, 
  jobapplicationstatus, 
  initialstatus, 
  dirtybit, 
  pageflowinstance, 
  TO_CHAR(datejaflockrelinquishes, 'YYYY-MM-DD HH24:MI:SS') datejaflockrelinquishes, 
  appliedforlocation_id, 
  createdby, 
  lastmodifiedby, 
  ismetajobbid::integer, 
  metajobbid_id, 
  wassaved::integer, 
  positionkey_id, 
  assessmentscore_id, 
  initialposting_id, 
  migratedversion, 
  uniqueapplicationid, 
  guuid, 
  isformeremployee::integer, 
  RehireEligibility, 
  i9taxwithholding_id, 
  w4taxwithholding_id, 
  scorebandsortvalue, 
  basepayamount, 
  basepayrate, 
  islocking::integer, 
  biddatenumber, 
  eobflowinstance, 
  videoconfirmation::integer, 
  overallphasescore_id, 
  scoredisplaylevel, 
  isquickapply::integer,
  jobtype,
  <BATCHDATE> as ExtractDate, 
  <BATCHDATE> as BatchDate, 
  <SOURCESKEY> as SourceSkey 
FROM 
  jobbid 
WHERE 
  (datelastmodified >= <FROMDATE_Q>)
