-- Query extracted from SSIS_SQLText
-- FlowSQLId: 146
-- FlowId: 146
-- DatabaseTypeId: 2
-- MinVersion: 8.5
-- MaxVersion: 999
-- Extracted on: 2025-05-25T17:11:39.346365

SELECT		workhistorycustomfield_id, 
				version, 
				cust_v_01, 
				cust_v_02, 
				cust_v_03, 
				cust_v_04, 
				cust_v_05, 
				cust_v_06, 
				cust_v_07, 
				cust_v_08, 
				cust_v_09, 
				cust_v_10, 
				cust_v_11, 
				cust_v_12, 
				cust_v_13, 
				cust_v_14, 
				cust_v_15, 
				cust_v_16, 
				cust_v_17, 
				cust_v_18, 
				cust_v_19, 
				cust_v_20,
				TO_CHAR(cust_d_01, 'YYYY-MM-DD HH24:MI:SS') as cust_d_01,
				TO_CHAR(cust_d_02, 'YYYY-MM-DD HH24:MI:SS') as cust_d_02, 
				TO_CHAR(cust_d_03, 'YYYY-MM-DD HH24:MI:SS') as cust_d_03, 
				TO_CHAR(cust_d_04, 'YYYY-MM-DD HH24:MI:SS') as cust_d_04, 
				TO_CHAR(cust_d_05, 'YYYY-MM-DD HH24:MI:SS') as cust_d_05, 
				TO_CHAR(cust_d_06, 'YYYY-MM-DD HH24:MI:SS') as cust_d_06,
				TO_CHAR(cust_d_07, 'YYYY-MM-DD HH24:MI:SS') as cust_d_07,
				TO_CHAR(cust_d_08, 'YYYY-MM-DD HH24:MI:SS') as cust_d_08, 
				TO_CHAR(cust_d_09, 'YYYY-MM-DD HH24:MI:SS') as cust_d_09, 
				TO_CHAR(cust_d_10, 'YYYY-MM-DD HH24:MI:SS') as cust_d_10, 
				TO_CHAR(cust_d_11, 'YYYY-MM-DD HH24:MI:SS') as cust_d_11, 
				TO_CHAR(cust_d_12, 'YYYY-MM-DD HH24:MI:SS') as cust_d_12, 
				TO_CHAR(cust_d_13, 'YYYY-MM-DD HH24:MI:SS') as cust_d_13,
				TO_CHAR(cust_d_14, 'YYYY-MM-DD HH24:MI:SS') as cust_d_14, 
				TO_CHAR(cust_d_15, 'YYYY-MM-DD HH24:MI:SS') as cust_d_15, 
				TO_CHAR(cust_d_16, 'YYYY-MM-DD HH24:MI:SS') as cust_d_16, 
				TO_CHAR(cust_d_17, 'YYYY-MM-DD HH24:MI:SS') as cust_d_17, 
				TO_CHAR(cust_d_18, 'YYYY-MM-DD HH24:MI:SS') as cust_d_18,
				TO_CHAR(cust_d_19, 'YYYY-MM-DD HH24:MI:SS') as cust_d_19,
				TO_CHAR(cust_d_20, 'YYYY-MM-DD HH24:MI:SS') as cust_d_20, 
 			    cust_n_01, 
				cust_n_02, 
				cust_n_03, 
				cust_n_04, 
				cust_n_05, 
				cust_n_06, 
				cust_n_07, 
				cust_n_08, 
				cust_n_09, 
				cust_n_10, 
				cust_n_11, 
				cust_n_12, 
				cust_n_13, 
				cust_n_14, 
				cust_n_15, 
				cust_n_16, 
				cust_n_17, 
				cust_n_18, 
				cust_n_19, 
				cust_n_20, 
				TO_CHAR(datecreated, 'YYYY-MM-DD HH24:MI:SS') as datecreated,  
	            TO_CHAR(datelastmodified, 'YYYY-MM-DD HH24:MI:SS') as datelastmodified, 
				createdby, 
				lastmodifiedby, 
				<BATCHDATE> as ExtractDate, 
				<BATCHDATE> as BatchDate, 
				<SOURCESKEY> as SourceSkey 
	 FROM workhistorycustomfield whcf
	 WHERE (datelastmodified >= <FROMDATE_Q>)